"""initial_schema

Revision ID: 7b72b070fd66
Revises: 
Create Date: 2026-02-11 11:29:21.339632

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import geoalchemy2

# revision identifiers, used by Alembic.
revision: str = '7b72b070fd66'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('territoire',
    sa.Column('id_territoire', sa.String(length=20), nullable=False, comment='Identifiant unique territoire'),
    sa.Column('code_insee', sa.String(length=5), nullable=False, comment='Code INSEE commune'),
    sa.Column('type_territoire', sa.String(length=20), nullable=False, comment='Type: COMMUNE, IRIS, BUREAU_VOTE, ARRONDISSEMENT'),
    sa.Column('nom_territoire', sa.String(length=100), nullable=False, comment='Nom lisible'),
    sa.Column('geometry', geoalchemy2.types.Geometry(geometry_type='POLYGON', srid=4326, dimension=2, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True, comment='Polygone géographique WGS84 (PostGIS)'),
    sa.Column('population', sa.Integer(), nullable=True, comment='Population totale'),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Métadonnées flexibles : superficie, coordonnées_centre, etc.'),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("type_territoire IN ('COMMUNE', 'IRIS', 'BUREAU_VOTE', 'ARRONDISSEMENT')", name='ck_territoire_type'),
    sa.CheckConstraint('population >= 0', name='ck_territoire_population'),
    sa.PrimaryKeyConstraint('id_territoire')
    )
    # Index geometry créé automatiquement par GeoAlchemy2
    op.create_index('idx_territoire_insee', 'territoire', ['code_insee'], unique=False)
    op.create_index('idx_territoire_type', 'territoire', ['type_territoire'], unique=False)
    op.create_table('type_indicateur',
    sa.Column('id_type', sa.Integer(), autoincrement=True, nullable=False, comment='Identifiant auto-incrémenté'),
    sa.Column('code_type', sa.String(length=50), nullable=False, comment='Code unique identifiant (MAJUSCULE_SNAKE_CASE)'),
    sa.Column('categorie', sa.String(length=50), nullable=False, comment='Catégorie macro'),
    sa.Column('nom_affichage', sa.String(length=100), nullable=False, comment='Libellé interface utilisateur'),
    sa.Column('description', sa.Text(), nullable=True, comment='Description détaillée'),
    sa.Column('unite_mesure', sa.String(length=50), nullable=True, comment='Unité : nombre, pourcentage, euros'),
    sa.Column('source_officielle', sa.String(length=100), nullable=True, comment='Organisme source'),
    sa.Column('frequence', sa.String(length=20), nullable=True, comment='Périodicité : ANNUEL, TRIMESTRIEL, MENSUEL'),
    sa.Column('date_debut_disponibilite', sa.Date(), nullable=True, comment='Première année disponible'),
    sa.Column('actif', sa.Boolean(), nullable=False, comment='Soft delete'),
    sa.Column('schema_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Schéma JSON validation métadonnées'),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id_type'),
    sa.UniqueConstraint('code_type')
    )
    op.create_index('idx_type_indicateur_categorie', 'type_indicateur', ['categorie'], unique=False)
    op.create_index('idx_type_indicateur_code', 'type_indicateur', ['code_type'], unique=False)
    op.create_table('election_result',
    sa.Column('id_result', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('id_territoire', sa.String(length=20), nullable=False),
    sa.Column('annee', sa.Integer(), nullable=False, comment='Année élection'),
    sa.Column('tour', sa.Integer(), nullable=False, comment='Tour (1 ou 2)'),
    sa.Column('candidat', sa.String(length=100), nullable=False, comment='Nom complet candidat'),
    sa.Column('parti', sa.String(length=50), nullable=True, comment='Parti politique'),
    sa.Column('nombre_voix', sa.Integer(), nullable=False, comment='Voix obtenues'),
    sa.Column('pourcentage_voix', sa.Numeric(precision=5, scale=2), nullable=False, comment='% voix exprimées'),
    sa.Column('nombre_inscrits', sa.Integer(), nullable=False, comment="Nombre d'inscrits"),
    sa.Column('nombre_votants', sa.Integer(), nullable=False, comment='Nombre de votants'),
    sa.Column('nombre_exprimes', sa.Integer(), nullable=False, comment='Nombre de voix exprimées'),
    sa.Column('taux_participation', sa.Numeric(precision=5, scale=2), nullable=False, comment='% participation'),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Métadonnées : nuance politique, etc.'),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('annee BETWEEN 2000 AND 2100', name='ck_election_annee'),
    sa.CheckConstraint('nombre_exprimes >= 0', name='ck_election_exprimes'),
    sa.CheckConstraint('nombre_inscrits >= 0', name='ck_election_inscrits'),
    sa.CheckConstraint('nombre_voix >= 0', name='ck_election_voix'),
    sa.CheckConstraint('nombre_votants >= 0', name='ck_election_votants'),
    sa.CheckConstraint('pourcentage_voix BETWEEN 0 AND 100', name='ck_election_pct_voix'),
    sa.CheckConstraint('taux_participation BETWEEN 0 AND 100', name='ck_election_taux_part'),
    sa.CheckConstraint('tour IN (1, 2)', name='ck_election_tour'),
    sa.ForeignKeyConstraint(['id_territoire'], ['territoire.id_territoire'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id_result'),
    sa.UniqueConstraint('id_territoire', 'annee', 'tour', 'candidat', name='unique_election_result')
    )
    op.create_index('idx_election_annee_tour', 'election_result', ['annee', 'tour'], unique=False)
    op.create_index('idx_election_candidat', 'election_result', ['candidat'], unique=False)
    op.create_index('idx_election_composite', 'election_result', ['id_territoire', 'annee', 'tour'], unique=False)
    op.create_index('idx_election_territoire', 'election_result', ['id_territoire'], unique=False)
    op.create_table('indicateur',
    sa.Column('id_indicateur', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('id_territoire', sa.String(length=20), nullable=False),
    sa.Column('id_type', sa.Integer(), nullable=False),
    sa.Column('annee', sa.Integer(), nullable=False, comment='Année référence (2000-2100)'),
    sa.Column('periode', sa.String(length=20), nullable=True, comment='T1-T4, M01-M12, NULL (annuel)'),
    sa.Column('valeur_numerique', sa.Numeric(precision=15, scale=4), nullable=True, comment='Valeur principale'),
    sa.Column('valeur_texte', sa.Text(), nullable=True, comment='Valeur qualitative'),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Métadonnées variables selon type'),
    sa.Column('source_detail', sa.String(length=200), nullable=True, comment='Source précise'),
    sa.Column('fiabilite', sa.String(length=20), nullable=False, comment='CONFIRME, ESTIME, PROVISOIRE, REVISION'),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("fiabilite IN ('CONFIRME', 'ESTIME', 'PROVISOIRE', 'REVISION')", name='ck_indicateur_fiabilite'),
    sa.CheckConstraint('annee BETWEEN 2000 AND 2100', name='ck_indicateur_annee'),
    sa.ForeignKeyConstraint(['id_territoire'], ['territoire.id_territoire'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id_type'], ['type_indicateur.id_type'], onupdate='CASCADE', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id_indicateur'),
    sa.UniqueConstraint('id_territoire', 'id_type', 'annee', 'periode', name='unique_indicateur')
    )
    op.create_index('idx_indicateur_annee', 'indicateur', ['annee'], unique=False)
    op.create_index('idx_indicateur_composite', 'indicateur', ['id_territoire', 'id_type', 'annee'], unique=False)
    op.create_index('idx_indicateur_metadata', 'indicateur', ['metadata'], unique=False, postgresql_using='gin')
    op.create_index('idx_indicateur_territoire', 'indicateur', ['id_territoire'], unique=False)
    op.create_index('idx_indicateur_type', 'indicateur', ['id_type'], unique=False)
    op.create_table('prediction',
    sa.Column('id_prediction', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('id_territoire', sa.String(length=20), nullable=False),
    sa.Column('candidat', sa.String(length=100), nullable=False, comment='Nom candidat prédit'),
    sa.Column('parti', sa.String(length=50), nullable=True, comment='Parti politique'),
    sa.Column('annee_prediction', sa.Integer(), nullable=True, comment='Année prédite'),
    sa.Column('tour', sa.Integer(), nullable=False, comment='Tour prédit (1 ou 2)'),
    sa.Column('pourcentage_predit', sa.Numeric(precision=5, scale=2), nullable=False, comment='% voix prédit'),
    sa.Column('intervalle_confiance_inf', sa.Numeric(precision=5, scale=2), nullable=True, comment='Borne inf IC 95%'),
    sa.Column('intervalle_confiance_sup', sa.Numeric(precision=5, scale=2), nullable=True, comment='Borne sup IC 95%'),
    sa.Column('modele_utilise', sa.String(length=50), nullable=False, comment='Nom du modèle ML'),
    sa.Column('version_modele', sa.String(length=20), nullable=True, comment='Version modèle (ex: v1.2.0)'),
    sa.Column('metriques_modele', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='R², MAE, RMSE, etc.'),
    sa.Column('features_utilisees', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Liste features ML'),
    sa.Column('date_generation', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('annee_prediction BETWEEN 2025 AND 2050', name='ck_prediction_annee'),
    sa.CheckConstraint('intervalle_confiance_inf BETWEEN 0 AND 100', name='ck_prediction_ic_inf'),
    sa.CheckConstraint('intervalle_confiance_sup BETWEEN 0 AND 100', name='ck_prediction_ic_sup'),
    sa.CheckConstraint('pourcentage_predit BETWEEN 0 AND 100', name='ck_prediction_pct'),
    sa.CheckConstraint('tour IN (1, 2)', name='ck_prediction_tour'),
    sa.ForeignKeyConstraint(['id_territoire'], ['territoire.id_territoire'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id_prediction'),
    sa.UniqueConstraint('id_territoire', 'candidat', 'tour', 'annee_prediction', 'version_modele', name='unique_prediction')
    )
    op.create_index('idx_prediction_annee', 'prediction', ['annee_prediction'], unique=False)
    op.create_index('idx_prediction_modele', 'prediction', ['modele_utilise'], unique=False)
    op.create_index('idx_prediction_territoire', 'prediction', ['id_territoire'], unique=False)
    # spatial_ref_sys est une table système PostGIS - ne pas supprimer
    # op.drop_table('spatial_ref_sys')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('spatial_ref_sys',
    sa.Column('srid', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('auth_name', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
    sa.Column('auth_srid', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('srtext', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    sa.Column('proj4text', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    sa.CheckConstraint('srid > 0 AND srid <= 998999', name=op.f('spatial_ref_sys_srid_check')),
    sa.PrimaryKeyConstraint('srid', name=op.f('spatial_ref_sys_pkey'))
    )
    op.drop_index('idx_prediction_territoire', table_name='prediction')
    op.drop_index('idx_prediction_modele', table_name='prediction')
    op.drop_index('idx_prediction_annee', table_name='prediction')
    op.drop_table('prediction')
    op.drop_index('idx_indicateur_type', table_name='indicateur')
    op.drop_index('idx_indicateur_territoire', table_name='indicateur')
    op.drop_index('idx_indicateur_metadata', table_name='indicateur', postgresql_using='gin')
    op.drop_index('idx_indicateur_composite', table_name='indicateur')
    op.drop_index('idx_indicateur_annee', table_name='indicateur')
    op.drop_table('indicateur')
    op.drop_index('idx_election_territoire', table_name='election_result')
    op.drop_index('idx_election_composite', table_name='election_result')
    op.drop_index('idx_election_candidat', table_name='election_result')
    op.drop_index('idx_election_annee_tour', table_name='election_result')
    op.drop_table('election_result')
    op.drop_index('idx_type_indicateur_code', table_name='type_indicateur')
    op.drop_index('idx_type_indicateur_categorie', table_name='type_indicateur')
    op.drop_table('type_indicateur')
    op.drop_index('idx_territoire_type', table_name='territoire')
    op.drop_index('idx_territoire_insee', table_name='territoire')
    op.drop_index('idx_territoire_geometry', table_name='territoire', postgresql_using='gist')
    op.drop_table('territoire')
    # ### end Alembic commands ###
