"""Create schema v3.0 - all models without geometry

Revision ID: 691a1578615b
Revises: 5c74986a8b20
Create Date: 2026-02-12 00:11:34.929770

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '691a1578615b'
down_revision: Union[str, Sequence[str], None] = '5c74986a8b20'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('candidat',
    sa.Column('id_candidat', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nom', sa.String(length=100), nullable=False),
    sa.Column('prenom', sa.String(length=100), nullable=False),
    sa.Column('nom_complet', sa.String(length=200), sa.Computed("prenom || ' ' || nom", ), nullable=True),
    sa.Column('date_naissance', sa.Date(), nullable=True),
    sa.Column('profession', sa.String(length=200), nullable=True),
    sa.Column('biographie', sa.Text(), nullable=True),
    sa.Column('photo_url', sa.String(length=500), nullable=True),
    sa.Column('metadata_', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('date_naissance IS NULL OR date_naissance <= CURRENT_DATE', name='check_date_naissance'),
    sa.PrimaryKeyConstraint('id_candidat')
    )
    op.create_index(op.f('ix_candidat_nom_complet'), 'candidat', ['nom_complet'], unique=False)
    op.create_table('parti',
    sa.Column('id_parti', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('code_parti', sa.String(length=20), nullable=False),
    sa.Column('nom_officiel', sa.String(length=200), nullable=False),
    sa.Column('nom_court', sa.String(length=100), nullable=True),
    sa.Column('classification_ideologique', sa.String(length=50), nullable=True),
    sa.Column('position_economique', sa.Numeric(precision=3, scale=2), nullable=True),
    sa.Column('position_sociale', sa.Numeric(precision=3, scale=2), nullable=True),
    sa.Column('couleur_hex', sa.String(length=7), nullable=True),
    sa.Column('logo_url', sa.String(length=500), nullable=True),
    sa.Column('date_creation', sa.Date(), nullable=True),
    sa.Column('date_dissolution', sa.Date(), nullable=True),
    sa.Column('successeur_id', sa.Integer(), nullable=True),
    sa.Column('metadata_', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("classification_ideologique IN ('extreme_gauche', 'gauche', 'centre_gauche', 'centre', 'centre_droit', 'droite', 'extreme_droite', 'autre')", name='check_classification_ideologique'),
    sa.CheckConstraint('date_dissolution IS NULL OR date_dissolution >= date_creation', name='check_dates_parti'),
    sa.CheckConstraint('position_economique BETWEEN -1.0 AND 1.0', name='check_position_economique'),
    sa.CheckConstraint('position_sociale BETWEEN -1.0 AND 1.0', name='check_position_sociale'),
    sa.ForeignKeyConstraint(['successeur_id'], ['parti.id_parti'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id_parti')
    )
    op.create_index(op.f('ix_parti_classification_ideologique'), 'parti', ['classification_ideologique'], unique=False)
    op.create_index(op.f('ix_parti_code_parti'), 'parti', ['code_parti'], unique=True)
    op.create_table('prediction',
    sa.Column('id_prediction', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('id_territoire', sa.String(length=15), nullable=False, comment='ID polymorphe du territoire'),
    sa.Column('type_territoire', sa.String(length=20), nullable=False, comment='Type de territoire'),
    sa.Column('candidat', sa.String(length=100), nullable=False, comment='Nom candidat prédit'),
    sa.Column('parti', sa.String(length=50), nullable=True, comment='Parti politique'),
    sa.Column('annee_prediction', sa.Integer(), nullable=True, comment='Année prédite'),
    sa.Column('tour', sa.Integer(), nullable=False, comment='Tour prédit (1 ou 2)'),
    sa.Column('pourcentage_predit', sa.Numeric(precision=5, scale=2), nullable=False, comment='% voix prédit'),
    sa.Column('intervalle_confiance_inf', sa.Numeric(precision=5, scale=2), nullable=True, comment='Borne inf IC 95%'),
    sa.Column('intervalle_confiance_sup', sa.Numeric(precision=5, scale=2), nullable=True, comment='Borne sup IC 95%'),
    sa.Column('modele_utilise', sa.String(length=50), nullable=False, comment='Nom du modèle ML'),
    sa.Column('version_modele', sa.String(length=20), nullable=True, comment='Version modèle (ex: v1.2.0)'),
    sa.Column('metriques_modele', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='R², MAE, RMSE, etc.'),
    sa.Column('features_utilisees', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Liste features ML'),
    sa.Column('date_generation', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("type_territoire IN ('BUREAU', 'CANTON', 'COMMUNE', 'ARRONDISSEMENT', 'DEPARTEMENT', 'REGION', 'NATIONAL')", name='ck_prediction_type_territoire'),
    sa.CheckConstraint('annee_prediction BETWEEN 2025 AND 2050', name='ck_prediction_annee'),
    sa.CheckConstraint('intervalle_confiance_inf BETWEEN 0 AND 100', name='ck_prediction_ic_inf'),
    sa.CheckConstraint('intervalle_confiance_sup BETWEEN 0 AND 100', name='ck_prediction_ic_sup'),
    sa.CheckConstraint('pourcentage_predit BETWEEN 0 AND 100', name='ck_prediction_pct'),
    sa.CheckConstraint('tour IN (1, 2)', name='ck_prediction_tour'),
    sa.PrimaryKeyConstraint('id_prediction'),
    sa.UniqueConstraint('id_territoire', 'type_territoire', 'candidat', 'tour', 'annee_prediction', 'version_modele', name='unique_prediction_territoire_type')
    )
    op.create_index('idx_prediction_annee', 'prediction', ['annee_prediction'], unique=False)
    op.create_index('idx_prediction_composite', 'prediction', ['id_territoire', 'type_territoire', 'annee_prediction'], unique=False)
    op.create_index('idx_prediction_modele', 'prediction', ['modele_utilise'], unique=False)
    op.create_index('idx_prediction_territoire', 'prediction', ['id_territoire', 'type_territoire'], unique=False)
    op.create_table('region',
    sa.Column('id_region', sa.String(length=2), nullable=False),
    sa.Column('code_insee', sa.String(length=2), nullable=False),
    sa.Column('nom_region', sa.String(length=100), nullable=False),
    sa.Column('population', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id_region')
    )
    op.create_table('type_election',
    sa.Column('id_type_election', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('code_type', sa.String(length=20), nullable=False),
    sa.Column('nom_type', sa.String(length=100), nullable=False),
    sa.Column('mode_scrutin', sa.String(length=50), nullable=True),
    sa.Column('niveau_geographique', sa.String(length=50), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("code_type IN ('PRES', 'LEG', 'MUN', 'EUR', 'REG', 'DEP', 'SENAT')", name='check_code_type'),
    sa.PrimaryKeyConstraint('id_type_election')
    )
    op.create_index(op.f('ix_type_election_code_type'), 'type_election', ['code_type'], unique=True)
    op.create_table('type_indicateur',
    sa.Column('id_type', sa.Integer(), autoincrement=True, nullable=False, comment='Identifiant auto-incrémenté'),
    sa.Column('code_type', sa.String(length=50), nullable=False, comment='Code unique identifiant (MAJUSCULE_SNAKE_CASE)'),
    sa.Column('categorie', sa.String(length=50), nullable=False, comment='Catégorie macro'),
    sa.Column('nom_affichage', sa.String(length=100), nullable=False, comment='Libellé interface utilisateur'),
    sa.Column('description', sa.Text(), nullable=True, comment='Description détaillée'),
    sa.Column('unite_mesure', sa.String(length=50), nullable=True, comment='Unité : nombre, pourcentage, euros'),
    sa.Column('source_officielle', sa.String(length=100), nullable=True, comment='Organisme source'),
    sa.Column('frequence', sa.String(length=20), nullable=True, comment='Périodicité : ANNUEL, TRIMESTRIEL, MENSUEL'),
    sa.Column('date_debut_disponibilite', sa.Date(), nullable=True, comment='Première année disponible'),
    sa.Column('actif', sa.Boolean(), nullable=False, comment='Soft delete'),
    sa.Column('schema_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Schéma JSON validation métadonnées'),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id_type'),
    sa.UniqueConstraint('code_type')
    )
    op.create_index('idx_type_indicateur_categorie', 'type_indicateur', ['categorie'], unique=False)
    op.create_index('idx_type_indicateur_code', 'type_indicateur', ['code_type'], unique=False)
    op.create_table('candidat_parti',
    sa.Column('id_affiliation', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_candidat', sa.Integer(), nullable=False),
    sa.Column('id_parti', sa.Integer(), nullable=False),
    sa.Column('date_debut', sa.Date(), nullable=False),
    sa.Column('date_fin', sa.Date(), nullable=True),
    sa.Column('fonction', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('date_fin IS NULL OR date_fin >= date_debut', name='check_dates_affiliation'),
    sa.ForeignKeyConstraint(['id_candidat'], ['candidat.id_candidat'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id_parti'], ['parti.id_parti'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id_affiliation'),
    sa.UniqueConstraint('id_candidat', 'id_parti', 'date_debut', name='uq_candidat_parti_date')
    )
    op.create_index(op.f('ix_candidat_parti_id_candidat'), 'candidat_parti', ['id_candidat'], unique=False)
    op.create_index(op.f('ix_candidat_parti_id_parti'), 'candidat_parti', ['id_parti'], unique=False)
    op.create_table('departement',
    sa.Column('id_departement', sa.String(length=3), nullable=False),
    sa.Column('id_region', sa.String(length=2), nullable=False),
    sa.Column('code_insee', sa.String(length=3), nullable=False),
    sa.Column('nom_departement', sa.String(length=100), nullable=False),
    sa.Column('population', sa.Integer(), nullable=True),
    sa.Column('chef_lieu', sa.String(length=5), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['id_region'], ['region.id_region'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id_departement')
    )
    op.create_index(op.f('ix_departement_id_region'), 'departement', ['id_region'], unique=False)
    op.create_table('election',
    sa.Column('id_election', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_type_election', sa.Integer(), nullable=False),
    sa.Column('annee', sa.Integer(), nullable=False),
    sa.Column('date_tour1', sa.Date(), nullable=False),
    sa.Column('date_tour2', sa.Date(), nullable=True),
    sa.Column('nombre_tours', sa.Integer(), server_default='1', nullable=False),
    sa.Column('contexte', sa.Text(), nullable=True),
    sa.Column('metadata_', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('annee BETWEEN 1900 AND 2100', name='check_annee'),
    sa.CheckConstraint('date_tour2 IS NULL OR date_tour2 > date_tour1', name='check_dates_tours'),
    sa.CheckConstraint('nombre_tours IN (1, 2)', name='check_nombre_tours'),
    sa.ForeignKeyConstraint(['id_type_election'], ['type_election.id_type_election'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id_election'),
    sa.UniqueConstraint('id_type_election', 'annee', 'date_tour1', name='uq_type_annee_date')
    )
    op.create_index(op.f('ix_election_annee'), 'election', ['annee'], unique=False)
    op.create_index(op.f('ix_election_id_type_election'), 'election', ['id_type_election'], unique=False)
    op.create_table('indicateur',
    sa.Column('id_indicateur', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('id_territoire', sa.String(length=15), nullable=False, comment='ID polymorphe du territoire'),
    sa.Column('type_territoire', sa.String(length=20), nullable=False, comment='Type de territoire'),
    sa.Column('id_type', sa.Integer(), nullable=False),
    sa.Column('annee', sa.Integer(), nullable=False, comment='Année référence (2000-2100)'),
    sa.Column('periode', sa.String(length=20), nullable=True, comment='T1-T4, M01-M12, NULL (annuel)'),
    sa.Column('valeur_numerique', sa.Numeric(precision=15, scale=4), nullable=True, comment='Valeur principale'),
    sa.Column('valeur_texte', sa.Text(), nullable=True, comment='Valeur qualitative'),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Métadonnées variables selon type'),
    sa.Column('source_detail', sa.String(length=200), nullable=True, comment='Source précise'),
    sa.Column('fiabilite', sa.String(length=20), nullable=False, comment='CONFIRME, ESTIME, PROVISOIRE, REVISION'),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("fiabilite IN ('CONFIRME', 'ESTIME', 'PROVISOIRE', 'REVISION')", name='ck_indicateur_fiabilite'),
    sa.CheckConstraint("type_territoire IN ('BUREAU', 'CANTON', 'COMMUNE', 'ARRONDISSEMENT', 'DEPARTEMENT', 'REGION', 'NATIONAL')", name='ck_indicateur_type_territoire'),
    sa.CheckConstraint('annee BETWEEN 2000 AND 2100', name='ck_indicateur_annee'),
    sa.ForeignKeyConstraint(['id_type'], ['type_indicateur.id_type'], onupdate='CASCADE', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id_indicateur'),
    sa.UniqueConstraint('id_territoire', 'type_territoire', 'id_type', 'annee', 'periode', name='unique_indicateur_territoire_type')
    )
    op.create_index('idx_indicateur_annee', 'indicateur', ['annee'], unique=False)
    op.create_index('idx_indicateur_composite', 'indicateur', ['id_territoire', 'type_territoire', 'id_type', 'annee'], unique=False)
    op.create_index('idx_indicateur_metadata', 'indicateur', ['metadata'], unique=False, postgresql_using='gin')
    op.create_index('idx_indicateur_territoire', 'indicateur', ['id_territoire', 'type_territoire'], unique=False)
    op.create_index('idx_indicateur_type', 'indicateur', ['id_type'], unique=False)
    op.create_index(op.f('ix_indicateur_annee'), 'indicateur', ['annee'], unique=False)
    op.create_index(op.f('ix_indicateur_id_type'), 'indicateur', ['id_type'], unique=False)
    op.create_table('canton',
    sa.Column('id_canton', sa.String(length=10), nullable=False),
    sa.Column('id_departement', sa.String(length=3), nullable=False),
    sa.Column('code_canton', sa.String(length=10), nullable=False),
    sa.Column('numero_canton', sa.Integer(), nullable=True),
    sa.Column('nom_canton', sa.String(length=100), nullable=False),
    sa.Column('population', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['id_departement'], ['departement.id_departement'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id_canton')
    )
    op.create_index(op.f('ix_canton_id_departement'), 'canton', ['id_departement'], unique=False)
    op.create_table('commune',
    sa.Column('id_commune', sa.String(length=5), nullable=False),
    sa.Column('id_departement', sa.String(length=3), nullable=False),
    sa.Column('code_insee', sa.String(length=5), nullable=False),
    sa.Column('nom_commune', sa.String(length=100), nullable=False),
    sa.Column('population', sa.Integer(), nullable=True),
    sa.Column('superficie_km2', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['id_departement'], ['departement.id_departement'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id_commune')
    )
    op.create_index(op.f('ix_commune_code_insee'), 'commune', ['code_insee'], unique=True)
    op.create_index(op.f('ix_commune_id_departement'), 'commune', ['id_departement'], unique=False)
    op.create_table('election_territoire',
    sa.Column('id_election_territoire', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_election', sa.Integer(), nullable=False),
    sa.Column('id_territoire', sa.String(length=15), nullable=False),
    sa.Column('type_territoire', sa.String(length=20), nullable=False),
    sa.Column('granularite_source', sa.String(length=20), nullable=False),
    sa.Column('date_import', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('source_fichier', sa.String(length=500), nullable=True),
    sa.Column('nombre_resultats_attendus', sa.Integer(), nullable=True),
    sa.Column('nombre_resultats_charges', sa.Integer(), nullable=True),
    sa.Column('statut_validation', sa.String(length=20), server_default='EN_COURS', nullable=False),
    sa.Column('metadata_', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("statut_validation IN ('EN_COURS', 'VALIDE', 'ERREUR', 'INCOMPLET')", name='check_statut_validation'),
    sa.CheckConstraint("type_territoire IN ('BUREAU', 'CANTON', 'COMMUNE', 'ARRONDISSEMENT', 'DEPARTEMENT', 'REGION', 'NATIONAL', 'CIRCONSCRIPTION')", name='check_type_territoire'),
    sa.CheckConstraint('nombre_resultats_charges IS NULL OR nombre_resultats_charges >= 0', name='check_nb_resultats'),
    sa.ForeignKeyConstraint(['id_election'], ['election.id_election'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id_election_territoire'),
    sa.UniqueConstraint('id_election', 'id_territoire', 'type_territoire', name='uq_election_territoire_type')
    )
    op.create_index(op.f('ix_election_territoire_id_election'), 'election_territoire', ['id_election'], unique=False)
    op.create_index(op.f('ix_election_territoire_statut_validation'), 'election_territoire', ['statut_validation'], unique=False)
    op.create_index(op.f('ix_election_territoire_type_territoire'), 'election_territoire', ['type_territoire'], unique=False)
    op.create_table('arrondissement',
    sa.Column('id_arrondissement', sa.String(length=10), nullable=False),
    sa.Column('id_commune', sa.String(length=5), nullable=False),
    sa.Column('numero_arrondissement', sa.Integer(), nullable=True),
    sa.Column('nom_arrondissement', sa.String(length=100), nullable=True),
    sa.Column('population', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['id_commune'], ['commune.id_commune'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id_arrondissement')
    )
    op.create_index(op.f('ix_arrondissement_id_commune'), 'arrondissement', ['id_commune'], unique=False)
    op.create_table('resultat_candidat',
    sa.Column('id_resultat_cand', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('id_election', sa.Integer(), nullable=False),
    sa.Column('id_candidat', sa.Integer(), nullable=False),
    sa.Column('id_territoire', sa.String(length=15), nullable=False),
    sa.Column('type_territoire', sa.String(length=20), nullable=False),
    sa.Column('tour', sa.Integer(), nullable=False),
    sa.Column('nombre_voix', sa.Integer(), nullable=False),
    sa.Column('pourcentage_voix_inscrits', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('pourcentage_voix_exprimes', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('metadata_', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("type_territoire IN ('BUREAU', 'CANTON', 'COMMUNE', 'ARRONDISSEMENT', 'DEPARTEMENT', 'REGION', 'NATIONAL')", name='check_type_territoire_candidat'),
    sa.CheckConstraint('nombre_voix >= 0', name='check_nombre_voix'),
    sa.CheckConstraint('pourcentage_voix_exprimes IS NULL OR pourcentage_voix_exprimes BETWEEN 0 AND 100', name='check_pct_exprimes'),
    sa.CheckConstraint('pourcentage_voix_inscrits IS NULL OR pourcentage_voix_inscrits BETWEEN 0 AND 100', name='check_pct_inscrits'),
    sa.CheckConstraint('tour IN (1, 2)', name='check_tour_candidat'),
    sa.ForeignKeyConstraint(['id_candidat'], ['candidat.id_candidat'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id_election', 'id_territoire', 'type_territoire'], ['election_territoire.id_election', 'election_territoire.id_territoire', 'election_territoire.type_territoire'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id_resultat_cand'),
    sa.UniqueConstraint('id_election', 'id_candidat', 'id_territoire', 'type_territoire', 'tour', name='uq_resultat_election_candidat_territoire_tour')
    )
    op.create_index(op.f('ix_resultat_candidat_id_candidat'), 'resultat_candidat', ['id_candidat'], unique=False)
    op.create_index(op.f('ix_resultat_candidat_id_election'), 'resultat_candidat', ['id_election'], unique=False)
    op.create_index(op.f('ix_resultat_candidat_tour'), 'resultat_candidat', ['tour'], unique=False)
    op.create_table('resultat_participation',
    sa.Column('id_resultat_part', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('id_election', sa.Integer(), nullable=False),
    sa.Column('id_territoire', sa.String(length=15), nullable=False),
    sa.Column('type_territoire', sa.String(length=20), nullable=False),
    sa.Column('tour', sa.Integer(), nullable=False),
    sa.Column('nombre_inscrits', sa.Integer(), nullable=False),
    sa.Column('nombre_abstentions', sa.Integer(), nullable=False),
    sa.Column('nombre_votants', sa.Integer(), nullable=False),
    sa.Column('nombre_blancs_nuls', sa.Integer(), nullable=False),
    sa.Column('nombre_exprimes', sa.Integer(), nullable=False),
    sa.Column('pourcentage_abstentions', sa.Numeric(precision=5, scale=2), sa.Computed('CASE WHEN nombre_inscrits > 0 THEN ROUND((nombre_abstentions::NUMERIC / nombre_inscrits * 100), 2) ELSE NULL END', ), nullable=True),
    sa.Column('pourcentage_votants', sa.Numeric(precision=5, scale=2), sa.Computed('CASE WHEN nombre_inscrits > 0 THEN ROUND((nombre_votants::NUMERIC / nombre_inscrits * 100), 2) ELSE NULL END', ), nullable=True),
    sa.Column('pourcentage_blancs_nuls_inscrits', sa.Numeric(precision=5, scale=2), sa.Computed('CASE WHEN nombre_inscrits > 0 THEN ROUND((nombre_blancs_nuls::NUMERIC / nombre_inscrits * 100), 2) ELSE NULL END', ), nullable=True),
    sa.Column('pourcentage_blancs_nuls_votants', sa.Numeric(precision=5, scale=2), sa.Computed('CASE WHEN nombre_votants > 0 THEN ROUND((nombre_blancs_nuls::NUMERIC / nombre_votants * 100), 2) ELSE NULL END', ), nullable=True),
    sa.Column('pourcentage_exprimes_inscrits', sa.Numeric(precision=5, scale=2), sa.Computed('CASE WHEN nombre_inscrits > 0 THEN ROUND((nombre_exprimes::NUMERIC / nombre_inscrits * 100), 2) ELSE NULL END', ), nullable=True),
    sa.Column('pourcentage_exprimes_votants', sa.Numeric(precision=5, scale=2), sa.Computed('CASE WHEN nombre_votants > 0 THEN ROUND((nombre_exprimes::NUMERIC / nombre_votants * 100), 2) ELSE NULL END', ), nullable=True),
    sa.Column('metadata_', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("type_territoire IN ('BUREAU', 'CANTON', 'COMMUNE', 'ARRONDISSEMENT', 'DEPARTEMENT', 'REGION', 'NATIONAL')", name='check_type_territoire_participation'),
    sa.CheckConstraint('nombre_abstentions >= 0', name='check_abstentions'),
    sa.CheckConstraint('nombre_blancs_nuls >= 0', name='check_blancs_nuls'),
    sa.CheckConstraint('nombre_exprimes + nombre_blancs_nuls = nombre_votants', name='check_coherence_votants'),
    sa.CheckConstraint('nombre_exprimes >= 0', name='check_exprimes'),
    sa.CheckConstraint('nombre_inscrits >= 0', name='check_inscrits'),
    sa.CheckConstraint('nombre_votants + nombre_abstentions = nombre_inscrits', name='check_coherence_inscrits'),
    sa.CheckConstraint('nombre_votants >= 0', name='check_votants'),
    sa.CheckConstraint('tour IN (1, 2)', name='check_tour_participation'),
    sa.ForeignKeyConstraint(['id_election', 'id_territoire', 'type_territoire'], ['election_territoire.id_election', 'election_territoire.id_territoire', 'election_territoire.type_territoire'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id_resultat_part'),
    sa.UniqueConstraint('id_election', 'id_territoire', 'type_territoire', 'tour', name='uq_participation_election_territoire_tour')
    )
    op.create_index(op.f('ix_resultat_participation_id_election'), 'resultat_participation', ['id_election'], unique=False)
    op.create_index(op.f('ix_resultat_participation_tour'), 'resultat_participation', ['tour'], unique=False)
    op.create_table('bureau_vote',
    sa.Column('id_bureau', sa.String(length=15), nullable=False),
    sa.Column('id_commune', sa.String(length=5), nullable=False),
    sa.Column('id_arrondissement', sa.String(length=10), nullable=True),
    sa.Column('code_bureau', sa.String(length=10), nullable=False),
    sa.Column('nom_bureau', sa.String(length=200), nullable=True),
    sa.Column('adresse', sa.Text(), nullable=True),
    sa.Column('nombre_inscrits', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['id_arrondissement'], ['arrondissement.id_arrondissement'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['id_commune'], ['commune.id_commune'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id_bureau'),
    sa.UniqueConstraint('id_commune', 'code_bureau', name='uq_commune_code_bureau')
    )
    op.create_index(op.f('ix_bureau_vote_id_arrondissement'), 'bureau_vote', ['id_arrondissement'], unique=False)
    op.create_index(op.f('ix_bureau_vote_id_commune'), 'bureau_vote', ['id_commune'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_bureau_vote_id_commune'), table_name='bureau_vote')
    op.drop_index(op.f('ix_bureau_vote_id_arrondissement'), table_name='bureau_vote')
    op.drop_table('bureau_vote')
    op.drop_index(op.f('ix_resultat_participation_tour'), table_name='resultat_participation')
    op.drop_index(op.f('ix_resultat_participation_id_election'), table_name='resultat_participation')
    op.drop_table('resultat_participation')
    op.drop_index(op.f('ix_resultat_candidat_tour'), table_name='resultat_candidat')
    op.drop_index(op.f('ix_resultat_candidat_id_election'), table_name='resultat_candidat')
    op.drop_index(op.f('ix_resultat_candidat_id_candidat'), table_name='resultat_candidat')
    op.drop_table('resultat_candidat')
    op.drop_index(op.f('ix_arrondissement_id_commune'), table_name='arrondissement')
    op.drop_table('arrondissement')
    op.drop_index(op.f('ix_election_territoire_type_territoire'), table_name='election_territoire')
    op.drop_index(op.f('ix_election_territoire_statut_validation'), table_name='election_territoire')
    op.drop_index(op.f('ix_election_territoire_id_election'), table_name='election_territoire')
    op.drop_table('election_territoire')
    op.drop_index(op.f('ix_commune_id_departement'), table_name='commune')
    op.drop_index(op.f('ix_commune_code_insee'), table_name='commune')
    op.drop_table('commune')
    op.drop_index(op.f('ix_canton_id_departement'), table_name='canton')
    op.drop_table('canton')
    op.drop_index(op.f('ix_indicateur_id_type'), table_name='indicateur')
    op.drop_index(op.f('ix_indicateur_annee'), table_name='indicateur')
    op.drop_index('idx_indicateur_type', table_name='indicateur')
    op.drop_index('idx_indicateur_territoire', table_name='indicateur')
    op.drop_index('idx_indicateur_metadata', table_name='indicateur', postgresql_using='gin')
    op.drop_index('idx_indicateur_composite', table_name='indicateur')
    op.drop_index('idx_indicateur_annee', table_name='indicateur')
    op.drop_table('indicateur')
    op.drop_index(op.f('ix_election_id_type_election'), table_name='election')
    op.drop_index(op.f('ix_election_annee'), table_name='election')
    op.drop_table('election')
    op.drop_index(op.f('ix_departement_id_region'), table_name='departement')
    op.drop_table('departement')
    op.drop_index(op.f('ix_candidat_parti_id_parti'), table_name='candidat_parti')
    op.drop_index(op.f('ix_candidat_parti_id_candidat'), table_name='candidat_parti')
    op.drop_table('candidat_parti')
    op.drop_index('idx_type_indicateur_code', table_name='type_indicateur')
    op.drop_index('idx_type_indicateur_categorie', table_name='type_indicateur')
    op.drop_table('type_indicateur')
    op.drop_index(op.f('ix_type_election_code_type'), table_name='type_election')
    op.drop_table('type_election')
    op.drop_table('region')
    op.drop_index('idx_prediction_territoire', table_name='prediction')
    op.drop_index('idx_prediction_modele', table_name='prediction')
    op.drop_index('idx_prediction_composite', table_name='prediction')
    op.drop_index('idx_prediction_annee', table_name='prediction')
    op.drop_table('prediction')
    op.drop_index(op.f('ix_parti_code_parti'), table_name='parti')
    op.drop_index(op.f('ix_parti_classification_ideologique'), table_name='parti')
    op.drop_table('parti')
    op.drop_index(op.f('ix_candidat_nom_complet'), table_name='candidat')
    op.drop_table('candidat')
    # ### end Alembic commands ###
