"""
Package de configuration pour l'extraction de données.

Expose toutes les constantes de configuration nécessaires au téléchargement.

Auteur: @de (Data Engineer)
"""

from .settings import (
    # Chemins
    PROJECT_ROOT,
    DATA_RAW,
    DATA_PROCESSED,
    DATA_RAW_ELECTIONS,
    DATA_RAW_SECURITE,
    DATA_RAW_GEOGRAPHIE,
    DATA_RAW_EMPLOI,
    # Géographie
    CODE_DEPARTEMENT,
    CODE_COMMUNE,
    NOM_COMMUNE,
    # URLs geo.api.gouv.fr
    GEO_API_BASE,
    GEO_REGIONS_URL,
    GEO_DEPARTEMENT_URL,
    GEO_COMMUNES_URL,
    # URLs Élections agrégées (v3)
    TABULAR_API_BASE,
    ELECTIONS_PARTICIPATION_RESOURCE,
    ELECTIONS_CANDIDATS_RESOURCE,
    ELECTIONS_NUANCES_RESOURCE,
    ELECTIONS_IDS,
    ELECTIONS_CANDIDATS_URL,
    ELECTIONS_NUANCES_URL,
    # URLs Élections anciennes
    ELECTIONS_2017_T1_URL,
    ELECTIONS_2017_T2_URL,
    ELECTIONS_2022_T1_URL,
    ELECTIONS_2022_T2_URL,
    ELECTIONS,
    # URLs Sécurité
    SECURITE_COMMUNALE_URL,
    # URLs Emploi
    EMPLOI_IRIS_BASE_URL,
    EMPLOI_BORDEAUX_DOSSIER_URL,
    # URLs Référentiels
    CORRESPONDANCE_BUREAU_IRIS_URL,
    CONTOURS_IRIS_URL,
    # Fichiers
    FICHIERS_GEOGRAPHIE,
    FICHIERS_ELECTIONS,
    FICHIERS_ELECTIONS_V3,
    FICHIER_SECURITE,
    FICHIERS_EMPLOI,
)

__all__ = [
    "PROJECT_ROOT",
    "DATA_RAW",
    "DATA_PROCESSED",
    "DATA_RAW_ELECTIONS",
    "DATA_RAW_SECURITE",
    "DATA_RAW_GEOGRAPHIE",
    "DATA_RAW_EMPLOI",
    "CODE_DEPARTEMENT",
    "CODE_COMMUNE",
    "NOM_COMMUNE",
    "GEO_API_BASE",
    "GEO_REGIONS_URL",
    "GEO_DEPARTEMENT_URL",
    "GEO_COMMUNES_URL",
    "TABULAR_API_BASE",
    "ELECTIONS_PARTICIPATION_RESOURCE",
    "ELECTIONS_CANDIDATS_RESOURCE",
    "ELECTIONS_NUANCES_RESOURCE",
    "ELECTIONS_IDS",
    "ELECTIONS_CANDIDATS_URL",
    "ELECTIONS_NUANCES_URL",
    "ELECTIONS_2017_T1_URL",
    "ELECTIONS_2017_T2_URL",
    "ELECTIONS_2022_T1_URL",
    "ELECTIONS_2022_T2_URL",
    "ELECTIONS",
    "SECURITE_COMMUNALE_URL",
    "EMPLOI_IRIS_BASE_URL",
    "EMPLOI_BORDEAUX_DOSSIER_URL",
    "CORRESPONDANCE_BUREAU_IRIS_URL",
    "CONTOURS_IRIS_URL",
    "FICHIERS_GEOGRAPHIE",
    "FICHIERS_ELECTIONS",
    "FICHIERS_ELECTIONS_V3",
    "FICHIER_SECURITE",
    "FICHIERS_EMPLOI",
]
