"""Package de configuration pour le module Load ETL v3.0."""

from .settings import (
    # Chemins
    REGIONS_CSV,
    DEPARTEMENTS_CSV,
    COMMUNES_CSV,
    PARTICIPATION_CSV,
    CANDIDATS_CSV,
    REFERENTIEL_CANDIDATS_CSV,
    REFERENTIEL_PARTIS_CSV,
    NUANCES_CSV,
    SECURITE_CSV,
    ELECTIONS_CSV,
    # Territoire
    CODE_COMMUNE,
    NOM_COMMUNE,
    TYPE_TERRITOIRE,
    POPULATION_BORDEAUX,
    # Types indicateurs
    TYPES_INDICATEURS,
    # Élections
    TYPE_ELECTION_PRES,
    ELECTIONS_CONFIG,
    NUANCE_CLASSIFICATION,
    CANDIDAT_PARTI_MAP,
    # Batch
    BATCH_SIZE,
    VERBOSE,
    # Validation
    ANNEES_ELECTIONS_VALIDES,
    ANNEES_INDICATEURS_VALIDES,
    TOURS_VALIDES,
)

__all__ = [
    "REGIONS_CSV",
    "DEPARTEMENTS_CSV",
    "COMMUNES_CSV",
    "PARTICIPATION_CSV",
    "CANDIDATS_CSV",
    "REFERENTIEL_CANDIDATS_CSV",
    "REFERENTIEL_PARTIS_CSV",
    "NUANCES_CSV",
    "SECURITE_CSV",
    "ELECTIONS_CSV",
    "CODE_COMMUNE",
    "NOM_COMMUNE",
    "TYPE_TERRITOIRE",
    "POPULATION_BORDEAUX",
    "TYPES_INDICATEURS",
    "TYPE_ELECTION_PRES",
    "ELECTIONS_CONFIG",
    "NUANCE_CLASSIFICATION",
    "CANDIDAT_PARTI_MAP",
    "BATCH_SIZE",
    "VERBOSE",
    "ANNEES_ELECTIONS_VALIDES",
    "ANNEES_INDICATEURS_VALIDES",
    "TOURS_VALIDES",
]
