"""
Package de configuration pour la transformation de données.

Auteur: @de (Data Engineer)
"""

from .settings import (
    PROJECT_ROOT,
    DATA_RAW,
    DATA_PROCESSED,
    DATA_RAW_ELECTIONS,
    DATA_RAW_SECURITE,
    DATA_RAW_GEOGRAPHIE,
    DATA_PROCESSED_ELECTIONS,
    DATA_PROCESSED_INDICATEURS,
    DATA_PROCESSED_GEOGRAPHIE,
    CODE_DEPARTEMENT,
    CODE_COMMUNE,
    NOM_COMMUNE,
    CODE_REGION,
    FICHIERS_GEOGRAPHIE,
    FICHIERS_ELECTIONS,
    FICHIERS_ELECTIONS_V3,
    ELECTIONS_IDS,
    FICHIER_SECURITE,
)

__all__ = [
    "PROJECT_ROOT",
    "DATA_RAW",
    "DATA_PROCESSED",
    "DATA_RAW_ELECTIONS",
    "DATA_RAW_SECURITE",
    "DATA_RAW_GEOGRAPHIE",
    "DATA_PROCESSED_ELECTIONS",
    "DATA_PROCESSED_INDICATEURS",
    "DATA_PROCESSED_GEOGRAPHIE",
    "CODE_DEPARTEMENT",
    "CODE_COMMUNE",
    "NOM_COMMUNE",
    "CODE_REGION",
    "FICHIERS_GEOGRAPHIE",
    "FICHIERS_ELECTIONS",
    "FICHIERS_ELECTIONS_V3",
    "ELECTIONS_IDS",
    "FICHIER_SECURITE",
]
